title       = "tuoitre"
baseURL     = "https://tuoitre-cli.tamnd.com/"
description = "A command line for tuoitre."
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/tuoitre-cli"
